sudo: required

services:
  - docker

before_install:
    - sudo apt-get update
    - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
    - docker --version # for verification
    - docket pull qwantresearch/alwilda:latest
    - docker build --cache-from qwantresearch/alwilda:latest -t qwantresearch/alwilda .
    - docker build -t alwilda_test -f Dockerfile_test .

script:
    - docker run alwilda_test 

notifications:
    email: false
